import pandas as pd
data4=pd.read_csv("C:/Users/SARAN K/Downloads/IDS_FootNoteMetaData.csv",encoding='latin1')
print(data4.shape)
print(data4.info())
print(data4.head())
print(data4.tail())
print(data4.columns)
print(data4.dtypes)
print("\n null values in data4:")
print(data4.isnull().sum())
print("\n print duplicate values in data4:")
print(data4.duplicated().sum())
data4['Country Name']=data4['Country Code'].str.extract(r'^(.*)\s\(')
data4['ISO Code']=data4['Country Code'].str.extract(r'\((.*?)\)')
data4['Year']=data4['Time Code'].str.extract(r'(\d{4})').astype(int)
data4['Year Code']=data4['Time Code'].str.extract(r'\((.*?)\)')
print(data4.shape)
print(data4.info())
print(data4.head())

